version: "3"
services:
  app:
    image: oring/app:${TAG}
    environment:
      - TIMESCALE_HOST=timescale-db
      - TIMESCALE_PORT=5432
      - TIMESCALE_USER=${POSTGRES_USER}
      - TIMESCALE_PASSWORD=${POSTGRES_PASSWORD}
      - TIMESCALE_DB=${POSTGRES_DB}
      - TIMESCALE_SCHEMA=${POSTGRES_SCHEMA}
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - NODE_ENV=production
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config

  redis:
    image: redis:latest
    ports:
      - 6379
    expose:
      - 6379
    volumes:
      - /docker-volumes/redis:/data

  timescale-db:
    image: timescale/timescaledb:latest-pg12
    env_file:
      - ./.env.prod
    ports:
      - 5432
    expose:
      - 5432
    volumes:
      - /docker-volumes/timescale-db:/var/lib/postgresql/data

  mongo:
    image: mongo:4.2.16
    env_file:
      - ./.env.prod
    ports:
      - 27017
    expose:
      - 27017
