version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    expose:
      - 6379

  # mongo:
  #   image: mongo:4.2.16
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: dev
  #     MONGO_INITDB_ROOT_PASSWORD: dev
  #   ports:
  #     - 27017:27017
  #   expose:
  #     - 27017

  # job:
  #   image: timescale/timescaledb:latest-pg12
  #   environment:
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=db3
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_PORT=5432
  #   volumes:
  #     - ./scripts/create-db.sh:/create-db.sh
  #   command:
  #     - ./create-db.sh
  #   depends_on:
  #     - postgres

  postgres:
    image: timescale/timescaledb:latest-pg12
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      # - PGDATA=/var/lib/postgresql/data/pgdata
      # - REPLICA_NAME=r1
      # - REPLICATE_FROM=postgres
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    expose:
      - 5432

#   postgres-master:
#     image: timescale/timescaledb:latest-pg12
#     environment:
#       REPLICATION_SUBNET: "0.0.0.0/0"
#       POSTGRES_USER: "postgres"
#       POSTGRES_PASSWORD: "PostGr3s2021"
#       POSTGRES_DB: "db"
#       REPLICA_POSTGRES_USER: "repuser"
#       REPLICA_POSTGRES_PASSWORD: "r3Puser"
#       PGDATA: "/var/lib/postgresql/data/pgdata"
#       REPLICA_NAME: "r1"
#       SYNCHRONOUS_COMMIT: "off"
#     volumes:
#       - postgres-master:/var/lib/postgresql/data
#       - ./scripts/replication.sh:/docker-entrypoint-initdb.d/replication.sh
#     ports:
#       - 54321:5432

#   postgres-slave:
#     image: timescale/timescaledb:latest-pg12
#     environment:
#       POSTGRES_USER: "repuser"
#       POSTGRES_PASSWORD: "r3Puser"
#       PGDATA: "/var/lib/postgresql/data/pgdata"
#       REPLICA_NAME: "r1"
#       REPLICATE_FROM: "postgres-master"
#     volumes:
#       - postgres-slave:/var/lib/postgresql/data
#       - ./scripts/replication.sh:/docker-entrypoint-initdb.d/replication.sh
#     ports:
#       - 54322:5432

#   timescale-proxy:
#     image: bitnami/pgpool:4
#     environment:
#       PGPOOL_BACKEND_NODES: "0:postgres-master:5432,1:postgres-slave:5432"
#       PGPOOL_SR_CHECK_USER: "repuser"
#       PGPOOL_SR_CHECK_PASSWORD: "r3Puser"
#       PGPOOL_ENABLE_LDAP: "no"
#       PGPOOL_POSTGRES_USERNAME: "postgres"
#       PGPOOL_POSTGRES_PASSWORD: "PostGr3s2021"
#       PGPOOL_POSTGRES_DB: "db"
#       PGPOOL_ADMIN_USERNAME: "admin"
#       PGPOOL_ADMIN_PASSWORD: "admin"
#     ports:
#       - 5432:5432

# volumes:
#   postgres-master:
#   postgres-slave:
