version: "3"
services:
  app:
    image: app:${TAG:-latest}
    depends_on:
      - redis
      - timescale-db

  redis:
    image: redis:latest

  timescale-db:
    image: timescale/timescaledb:latest-pg12

  mongo:
    image: mongo:4.2.16
